// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwp0wyRfbofNvhkss4SxMcLOAyjqthMCg',
    appId: '1:992872780530:web:36e57291674f219c9bf66b',
    messagingSenderId: '992872780530',
    projectId: 'ditonton-77939',
    authDomain: 'ditonton-77939.firebaseapp.com',
    storageBucket: 'ditonton-77939.appspot.com',
    measurementId: 'G-S2ZZF51QWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNIJYSBkCGPxw-aY5arGlqpJ2N7OFJEac',
    appId: '1:992872780530:android:49b02cbed694f60f9bf66b',
    messagingSenderId: '992872780530',
    projectId: 'ditonton-77939',
    storageBucket: 'ditonton-77939.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdoz4lbWeE9TVmiemstQoiqsGNKJ4a69I',
    appId: '1:992872780530:ios:676a5d7e7b756c099bf66b',
    messagingSenderId: '992872780530',
    projectId: 'ditonton-77939',
    storageBucket: 'ditonton-77939.appspot.com',
    iosClientId: '992872780530-c8nstqptjkcjo3nnvfivb4hkvml2i2g8.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
